/** Hands generated bytes to the browser as a download named `filename`. */
export function saveFile(bytes: Uint8Array, filename: string, mimeType: string): void {
  const url = URL.createObjectURL(new Blob([new Uint8Array(bytes)], { type: mimeType }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.rel = "noopener";
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  // Revoked on the next task, once the browser has started the download.
  setTimeout(() => URL.revokeObjectURL(url), 0);
}
