export const STORAGE_CLEANUP_MILLISECONDS_PER_HOUR = 60 * 60 * 1_000;
export const STORAGE_DELETION_ERROR_CODE = "S3_DELETE_FAILED";
export const STORAGE_CLEANUP_CACHE_CONTROL_HEADER = "cache-control";
export const STORAGE_CLEANUP_PRIVATE_CACHE_CONTROL = "no-store";
export const STORAGE_CLEANUP_FORBIDDEN_STATUS = 403;
export const STORAGE_CLEANUP_UNAVAILABLE_STATUS = 503;
export const STORAGE_CLEANUP_FORBIDDEN_CODE = "FORBIDDEN";
export const STORAGE_CLEANUP_UNAVAILABLE_CODE = "SERVICE_UNAVAILABLE";
export const STORAGE_CLEANUP_FORBIDDEN_MESSAGE = "The request is not allowed.";
export const STORAGE_CLEANUP_UNAVAILABLE_MESSAGE =
  "Storage cleanup is temporarily unavailable.";
