export const MINIMUM_STORAGE_DELETION_BATCH_SIZE = 1;
export const MAXIMUM_STORAGE_DELETION_BATCH_SIZE = 100;
export const EXPIRED_UPLOAD_REASON = "UPLOAD_EXPIRED";
export const USER_REMOVED_UPLOAD_REASON = "UPLOAD_REMOVED_BY_USER";
