packages:
  - apps/*
  - packages/*
  - workers/*

allowBuilds:
  '@prisma/engines': true
  prisma: true
  unrs-resolver: true

catalog:
  '@prisma/adapter-pg': 7.10.0
  '@prisma/client': 7.10.0
  '@types/pg': 8.23.1
  pg: 8.23.0
  prisma: 7.10.0
  openid-client: 6.8.8
  zod: 4.6.5
