export const EMAIL_MESSAGE_TYPE = "PROCESSING_COMPLETED";
export const EMAIL_MESSAGE_VERSION = 1;
export const EMAIL_QUEUE_PUBLISH_ERROR_CODE = "EMAIL_QUEUE_PUBLISH_FAILED";
export const EMAIL_DELIVERY_DATA_INVALID_ERROR_CODE =
  "EMAIL_DELIVERY_DATA_INVALID";
export const EMAIL_DELIVERY_UNEXPECTED_ERROR_CODE =
  "EMAIL_DELIVERY_UNEXPECTED_ERROR";
export const EMAIL_DELIVERY_ACKNOWLEDGED = "ACKNOWLEDGED";
export const EMAIL_DELIVERY_RETRY = "RETRY";
export const EMAIL_DELIVERY_CLAIMED = "CLAIMED";
export const EMAIL_DELIVERY_NOT_READY = "NOT_READY";
export const EMAIL_DELIVERY_TERMINAL = "TERMINAL";
export const MAIL_DELIVERY_DELIVERED = "DELIVERED";
export const MAIL_DELIVERY_FAILED = "FAILED";
export const MINIMUM_EMAIL_BATCH_SIZE = 1;
export const MAXIMUM_EMAIL_BATCH_SIZE = 100;
export const MINIMUM_EMAIL_CLAIM_TTL_MILLISECONDS = 1_000;
export const MAXIMUM_EMAIL_CLAIM_TTL_MILLISECONDS = 300_000;
export const MINIMUM_EMAIL_RETRY_MILLISECONDS = 100;
export const MAXIMUM_EMAIL_RETRY_MILLISECONDS = 3_600_000;
